/*
    Drools5 Integration Helper
    Copyright (C) 2009  Mathieu Boretti mathieu.boretti@gmail.com

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package com.grandsea.conditions;

global org.apache.log4j.Logger droolsLogger;


rule "Wrong customer 1"
when
	c:Customer(chomeur == true)
then
	insert(new UnAuthorizedError("Chomeur are not allowed"));
end

rule "Wrong customer 2"
when
	c:Customer(sexe == false, age<=45)
then
	insert(new UnAuthorizedError("Bad sex with age under 45 are not allowed"));
end